/**
 * Known runtime sources that can emit React Log Agent events.
 */
export type LogSource = "fetch" | "axios" | "router";

/**
 * Capture modes negotiated by the CLI bridge during startup.
 */
export type CaptureProfile = "network" | "routes" | "errors" | "all";

/**
 * Adapter identifier announced by the browser SDK during handshake.
 *
 * The built-in adapters use {@link LogSource}; custom adapters may provide
 * their own stable string identifiers.
 */
export type AdapterName = LogSource | (string & {});

/**
 * Payload shape after the runtime SDK has sanitized, redacted, and normalized
 * it for transport across the protocol boundary.
 */
export type SerializablePayload = unknown;

/**
 * Normalized HTTP headers represented as lowercase or original header names
 * mapped to string values.
 */
export type HeaderMap = Record<string, string>;

/**
 * Route context attached to non-route events when the runtime SDK can identify
 * the active route.
 */
export interface CurrentRouteContext {
  /** Active route path at the time the event was emitted. */
  path: string;
  /** Navigation identifier associated with the active route, when available. */
  navigationId?: string;
  /** Browser document title or router-provided route title, when available. */
  title?: string;
}

/**
 * Common metadata shared by every log event.
 */
export interface BaseEvent {
  /** Unique event identifier generated by the browser SDK. */
  id: string;
  /** CLI/runtime session identifier shared during the bridge connection. */
  sessionId: string;
  /** Unix epoch timestamp in milliseconds. */
  timestamp: number;
  /** Runtime source that emitted the event. */
  source: LogSource;
  /** Active route context, when available for the emitting adapter. */
  currentRouteContext?: CurrentRouteContext;
}

/**
 * Route transition emitted by a router adapter.
 */
export interface RouteTransitionEvent extends Omit<BaseEvent, "source"> {
  type: "ROUTE_TRANSITION";
  source: "router";
  /** Previous route path. */
  from: string;
  /** New route path. */
  to: string;
  /** Identifier used to correlate route changes with nearby network events. */
  navigationId: string;
}

/**
 * Sources that can emit HTTP events.
 */
export type HttpLogSource = Extract<LogSource, "fetch" | "axios">;

/**
 * Outgoing HTTP request emitted before the runtime forwards the original call.
 */
export interface HttpRequestEvent extends Omit<BaseEvent, "source"> {
  type: "HTTP_REQUEST";
  source: HttpLogSource;
  /** Uppercase HTTP method such as GET, POST, PUT, or DELETE. */
  method: string;
  /** Fully resolved request URL when available. */
  url: string;
  /** Normalized request headers after redaction. */
  headers: HeaderMap;
  /** Sanitized request body. Large bodies may be truncated before transport. */
  body?: SerializablePayload;
  /** Stable identifier used to pair request, response, and error events. */
  requestId: string;
}

/**
 * Incoming HTTP response emitted after the original call resolves.
 */
export interface HttpResponseEvent extends Omit<BaseEvent, "source"> {
  type: "HTTP_RESPONSE";
  source: HttpLogSource;
  /** Numeric HTTP status code returned by the server. */
  status: number;
  /** Normalized response headers after redaction. */
  headers: HeaderMap;
  /** Sanitized response body. Large bodies may be truncated before transport. */
  body?: SerializablePayload;
  /** Request duration in milliseconds. */
  latency: number;
  /** Stable identifier used to pair request, response, and error events. */
  requestId: string;
}

/**
 * HTTP failure emitted when the original request rejects or cannot be completed.
 */
export interface HttpErrorEvent extends Omit<BaseEvent, "source"> {
  type: "HTTP_ERROR";
  source: HttpLogSource;
  /** Error class or name reported by the underlying client. */
  errorName: string;
  /** Human-readable error message reported by the underlying client. */
  errorMessage: string;
  /** Optional client-specific error code such as ECONNABORTED. */
  code?: string;
  /** Request duration in milliseconds when it can be measured. */
  latency?: number;
  /** Stable identifier used to pair request, response, and error events. */
  requestId: string;
}

/**
 * Discriminated union of every event accepted by the React Log Agent protocol.
 */
export type LogEvent =
  | RouteTransitionEvent
  | HttpRequestEvent
  | HttpResponseEvent
  | HttpErrorEvent;

/**
 * Browser SDK hello message sent when the runtime attempts to connect to the
 * local CLI bridge.
 */
export interface ClientHelloPayload {
  kind: "CLIENT_HELLO";
  /** Human-readable application name shown by the CLI dashboard. */
  appName: string;
  /** Browser SDK package version. */
  sdkVersion: string;
  /** Runtime adapters available in the current application. */
  availableAdapters: AdapterName[];
}

/**
 * CLI acknowledgement that activates a capture profile in the browser runtime.
 */
export interface ServerAckPayload {
  kind: "SERVER_ACK";
  /** Capture profile selected by the CLI session. */
  activeProfile: CaptureProfile;
  /** Redaction rules supplied remotely by the CLI session. */
  remoteRedactRules: string[];
  /** URL or route filter patterns supplied by the CLI session. */
  filterPatterns: string[];
}

/**
 * Handshake payloads exchanged before runtime instrumentation is activated.
 */
export type HandshakePayload = ClientHelloPayload | ServerAckPayload;

/**
 * Stable event discriminants supported by this protocol version.
 */
export const LOG_EVENT_TYPES = [
  "ROUTE_TRANSITION",
  "HTTP_REQUEST",
  "HTTP_RESPONSE",
  "HTTP_ERROR",
] as const satisfies readonly LogEvent["type"][];

/**
 * Built-in runtime sources supported by this protocol version.
 */
export const LOG_SOURCES = ["fetch", "axios", "router"] as const satisfies readonly LogSource[];

/**
 * Capture profiles supported by CLI/runtime negotiation.
 */
export const CAPTURE_PROFILES = [
  "network",
  "routes",
  "errors",
  "all",
] as const satisfies readonly CaptureProfile[];

/**
 * Handshake message kinds supported by CLI/runtime negotiation.
 */
export const HANDSHAKE_KINDS = [
  "CLIENT_HELLO",
  "SERVER_ACK",
] as const satisfies readonly HandshakePayload["kind"][];
